---
adguard_version: "0.107.72"

adguard_upstream_dns:
  - "1.1.1.1"
  - "8.8.8.8"

adguard_bootstrap_dns:
  - "1.1.1.1"

adguard_dns_port: 53
adguard_web_port: 3000

adguard_data_dir: "/opt/adguardhome"

adguard_custom_dns:
  - domain: "vpn.bricoo.fr"
    answer: "10.10.0.10"
  - domain: "portainer.bricoo.fr"
    answer: "10.10.0.10"
  - domain: "files.bricoo.fr"
    answer: "10.10.0.10"
  - domain: "pwd.bricoo.fr"
    answer: "10.10.0.10"
  - domain: "adguard.bricoo.fr"
    answer: "10.10.0.10"
  - domain: "couchdb.bricoo.fr"
    answer: "10.10.0.10"
  - domain: "pve-01.bricoo.fr"
    answer: "10.10.0.10"

# DHCP server
adguard_dhcp_enabled: false
adguard_dhcp_interface: "eth0"
adguard_dhcp_domain: "lan"
adguard_dhcp_gateway: "10.40.0.1"
adguard_dhcp_subnet_mask: "255.255.0.0"
adguard_dhcp_range_start: "10.40.0.100"
adguard_dhcp_range_end: "10.40.0.105"
adguard_dhcp_lease_duration: 86400
