---
- name: Setting up network interfaces
  block:
    - name: Deploy interfaces configuration
      ansible.builtin.template:
        src: interfaces.j2
        dest: /etc/network/interfaces
        owner: root
        group: root
        mode: '0644'
        backup: true
      notify: Reload network
  become: true

- name: Configure SSH for Packer reverse tunnels
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^#?GatewayPorts'
    line: 'GatewayPorts clientspecified'
  become: true
  notify: Restart sshd
