---
portainer_server_image: "portainer/portainer-ce:2.40.0"
portainer_agent_image: "portainer/agent:2.40.0"

portainer_server_data_dir: "/opt/portainer-server"
portainer_agent_data_dir: "/opt/portainer-agent"

portainer_nodes: []
