---
- name: Setup firewall configuration
  block:
    - name: Deploy nftables configuration
      ansible.builtin.template:
        src: nftables-base.conf.j2
        dest: /etc/nftables.conf
        owner: root
        group: root
        mode: '0600'
        backup: true
      notify: Restart nftables

    - name: Ensure nftables service is enabled
      ansible.builtin.systemd_service:
        name: nftables.service
        state: started
        enabled: true
  become: true

- name: Setup sysctl configuration
  block:
    - name: Deploy sysctl configuration
      ansible.builtin.template:
        src: sysctl.conf.j2
        dest: /etc/sysctl.conf
        owner: root
        group: root
        mode: '0644'

    - name: Apply sysctl configuration
      ansible.builtin.command: sysctl -p
      changed_when: false
  become: true

- name: Deploy DNS configuration
  ansible.builtin.import_tasks: dns.yaml

- name: Disable unattended upgrades
  ansible.builtin.systemd_service:
    name: unattended-upgrades
    state: stopped
    enabled: false
  become: true
  ignore_errors: true
