all:
  children:
    proxmox:
      hosts:
        pve_01:
          ansible_host: 152.228.222.18
      vars:
        ansible_user: root
        ansible_ssh_private_key_file: ~/.ssh/ovh-pve-01
    firewall:
      hosts:
        homelab-firewall:
          ansible_host: 152.228.222.18
          ansible_port: 2222
          ansible_user: brico
          ansible_ssh_private_key_file: ~/.ssh/ovh-homelab
      vars:
    
    infra:
      hosts:
        homelab-vpn:
          ansible_host: 10.30.0.10
        homelab-pihole:
          ansible_host: 10.10.0.10
        homelab-admin:
          ansible_host: 10.20.0.10
      vars:
        ansible_user: brico
        ansible_ssh_private_key_file: ~/.ssh/ovh-homelab   
