---
pihole_interface: "eth0"
pihole_upstream_dns_1: "1.1.1.1"
pihole_upstream_dns_2: "8.8.8.8"
pihole_web_password: ""

nftables_extra_rules:
  - 'tcp dport 53 accept comment "DNS TCP"'
  - 'udp dport 53 accept comment "DNS UDP"'
  - 'tcp dport 80 accept comment "Pi-hole web UI"'
