---
- name: Restart portainer server
  ansible.builtin.command:
    cmd: docker compose restart
    chdir: "{{ portainer_server_data_dir }}"
  become: true

- name: Restart portainer agent
  ansible.builtin.command:
    cmd: docker compose restart
    chdir: "{{ portainer_agent_data_dir }}"
  become: true
