---
- name: Setting up tailscale
  block:
    - name: Add Tailscale GPG key
      ansible.builtin.shell: >
        curl -fsSL https://pkgs.tailscale.com/stable/debian/trixie.noarmor.gpg
        | tee /usr/share/keyrings/tailscale-archive-keyring.gpg >/dev/null
      args:
        creates: /usr/share/keyrings/tailscale-archive-keyring.gpg

    - name: Add Tailscale repository
      ansible.builtin.shell: >
        curl -fsSL https://pkgs.tailscale.com/stable/debian/trixie.tailscale-keyring.list
        | tee /etc/apt/sources.list.d/tailscale.list
      args:
        creates: /etc/apt/sources.list.d/tailscale.list

    - name: Install tailscale
      ansible.builtin.apt:
        pkg:
          - tailscale
        update_cache: true

  become: true
