---
- name: Setting up networking
  block:
    - name: Copy disable Cloud-Init networking file
      ansible.builtin.copy:
        src: 99-custom-networking.cfg
        dest: /etc/cloud/cloud.cfg.d/99-custom-networking.cfg
        owner: root
        group: root
        mode: '0644'

    - name: Install vlan package
      ansible.builtin.apt:
        pkg:
          - vlan
        update_cache: true

    - name: Load 8021q module
      ansible.builtin.command: modprobe 8021q
      changed_when: false

    - name: Ensure 8021q module loads at boot
      ansible.builtin.lineinfile:
        path: /etc/modules
        line: "8021q"
        state: present

    - name: Deploy interfaces configuration
      ansible.builtin.template:
        src: interfaces.j2
        dest: /etc/network/interfaces
        owner: root
        group: root
        mode: '0644'
        backup: true
      register: network_config

    - name: Restart networking
      ansible.builtin.systemd_service:
        name: networking.service
        state: restarted
        enabled: true
      when: network_config.changed

    - name: Ensure VLAN interfaces are up
      ansible.builtin.command: ifup eth0.{{ item }}
      loop: "{{ firewall_vlans | map(attribute='id') }}"
      changed_when: false
      failed_when: false

  become: true
