---
- name: Restart networking
  ansible.builtin.systemd_service:
    name: networking.service
    state: restarted
    enabled: true
  become: true

- name: Restart nftables
  ansible.builtin.systemd_service:
    name: nftables.service
    state: restarted
    enabled: true
  become: true

- name: Restart dhcp-relay
  ansible.builtin.systemd_service:
    name: isc-dhcp-relay
    state: restarted
    enabled: true
  become: true
